# Generated by Django 4.2.3 on 2023-08-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correo',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='correo',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
